### ISSUE TITLE
Compatibility with Ad Astra

### ISSUE THREAD

**Issue by Nova-Katt** [JustDoom/VillagerInABucket#1]
Hi!

[Ad Astra](https://modrinth.com/mod/ad-astra) adds several planets to explore via rockets, and they have new monsters and villagers.
It would be amazing if the Lunarians would be bucketable.
They are basically reskinned Villagers that function the same way on the Moon as the usual villagers do on the regular overworld.

Due to the villager thing, they CAN technically be picked up already, but they are converted to Plains Villagers, which means I don't actually get the Lunarian, aaaaand they would fit so well with the theme I'm building on a server with some friends where I play as sort of an "alien visitor" in my builds, so having Lunarians instead of Villagers would fit perfectly.

**Comment by JustDoom** [comment]
I shall have a look into it, what Minecraft version specifically does this occur in?

**Comment by Nova-Katt** [comment]
> I shall have a look into it, what Minecraft version specifically does this occur in?

Amazing.
I am currently running 1.20.4, but we will eventually update to 1.21 once some more mods that we use catch up, so I guess a bit of both. :P

**Comment by JustDoom** [comment]
Alright, the latest update should fix this issue. Versions 1.20.1-1.3.0 and above and 1.20.2-1.2.0 and above support it. As of writing this, curseforge is processing the files but they are available on Modrinth now (https://modrinth.com/mod/villager-in-a-bucket/versions).

If there are any problems please open a new issue. I did testing so there shouldn't be any but please do some testing to double check.

**Comment by Nova-Katt** [comment]
Can confirm. Seems to work now, thank you! :D
