### ISSUE TITLE
1.21 update

### ISSUE THREAD

**Issue by vico93** [JustDoom/VillagerInABucket#2]
Is an update to 1.21 in the plans?

**Comment by JustDoom** [comment]
It is, the main branch contains progress for it. I am having trouble getting it working since 1.20.6 changed how this stuff worked

**Comment by JustDoom** [comment]
Soon my friend, soon. 1.20.6 is working, tomorrow I shall update to 1.21(.1)

**Comment by JustDoom** [comment]
Done! Fabric supports 1.21 and 1.21.1 and Forge/NeoForge supports 1.21.1
If you specifically need 1.21 support for Forge/NeoForge please just respond here and I shall work on it
