### ISSUE TITLE
Zombie Villager Support

### ISSUE THREAD

**Issue by Yo-Snowpro** [JustDoom/VillagerInABucket#4]
Allow for the ability to place Zombie Villagers in a water bucket (so they dont burn)

**Comment by JustDoom** [comment]
So you just want a Zombie Villager In A Bucket item?

**Comment by Yo-Snowpro** [comment]
Yeah, thats it... :/

**Comment by JustDoom** [comment]
I will think about it. Not sure how well being able to pick up a hostile mob will fit in this mod, even if it is only the Villager version

**Comment by JustDoom** [comment]
I am considering adding it along with an option to disable collecting them in a bucket if the feature is unwanted

**Comment by JustDoom** [comment]
Almost forgot. @Yo-Snowpro I have added a Zombie Villager In A Bucket with an option to disable it in the new config! 1.20.4 and 1.20.1 have it so far and slowly will update the other versions
